### ISSUE TITLE
Text filtering in transcripts (uh, like)

### ISSUE THREAD

**Issue by AstroFloof** [Satisfactory-Clips-Archive/Media-Search-Archive#18]
- [x] de-hesitate channel clip transcriptions
- [ ] de-hesitate external clip transcriptions
- [x] de-hesitate lunr indexes
`^edits by marv to make github UI happy`

**So uh, I can't like... read this**
Transcripts are frequently barely readable due to continuously transliterating everything, including hesitation interjections such as "uh", "um", and "like".

**What can uh, be done?**
Some sort of filtering to remove these words and break up text based on periods of silence in a video.

**But like, how?**
This might be possible with regular expressions for the "uh" and "um" stuff, but "like" is a trickier case and might need some NLP. I'm not familiar with NLP in detail but it sounds like the kind of thing you can do with it. The text breaks might also be tricky, unless you find a transcription software better than what you're already using (stock youtube auto-captions right?)

This is a somewhat far-fetched and low-gain feature request, but imho it would improve the archive.

**Comment by SignpostMarv** [comment]
would agree that "like" would have too many false positives without NLP.

I have looked into doing auto-transcriptions independently of YouTube, but I've not found the time to do it properly (train a model on the videos) rather than using a prebuilt model.

**Comment by SignpostMarv** [comment]
- [ ] de-hesitate channel clip transcriptions
- [ ] de-hesitate external clip transcriptions

**Comment by SignpostMarv** [comment]
example of fixes applied:

before:
> um our coffee state is back at the office now because they had to work at home with covet we didn't have to work at home with covid but um uh we have been working many people have been working back at the office for quite some time now uh but not everyone yet some of us still work from home yeah and i don't think uh but everyone is back we were away from the office for vacation that that is over that ended uh like last month and we've had a second like uh set of restrictions in sweden um that like kind of ended last week sort of and so maybe people will start popping up more we're still kind of renovating at the office so like i don't know but people kind of mix mix a little bit now and maybe that's how it's going to go in the future too like people mix and match like a little bit if they work from home someday so if they work at the office like half days or something
> 
> [Music]
> 
> that's for the future to tell

after:
> our coffee state is back at the office now because they had to work at home with covet we didn't have to work at home with covid but, we have been working many people have been working back at the office for quite some time now, but not everyone yet some of us still work from home yeah and I don't think, but everyone is back we were away from the office for vacation that that is over that ended, like last month and we've had a second like, set of restrictions in sweden, that like kind of ended last week sort of and so maybe people will start popping up more we're still kind of renovating at the office so like I don't know but people kind of mix mix a little bit now and maybe that's how it's going to go in the future too like people mix and match like a little bit if they work from home someday so if they work at the office like half days or something
> 
> [Music]
> 
> that's for the future to tell

**Comment by SignpostMarv** [comment]
example of clip with manual transcription that still has the hesitations in: https://archive.satisfactory.video/transcriptions/yt-zHYxze67E28/

**Comment by SignpostMarv** [comment]
@AstroFloof there's currently only 19 matches for "uh", and 5 matches for "um"- they all look like they're either from manually-transcribed stuff in the metadata repo, or direct from Coffee Stain's professional™ subtitles.

Is it acceptable to close this ticket as-is?

**Comment by AstroFloof** [comment]
Is that post- or pre- all the stuff you just did?

**Comment by SignpostMarv** [comment]
that's with just yesterday's work.

the only reason to move ahead with ensuring external clips were dehesitated would be if I were to start indexing third-party stuff (like E3 interviews etc.) that might not have manually edited subtitles on them.

**Comment by AstroFloof** [comment]
What you've done already is probably enough to make things a little more readable, thank you.
If you want you can close this, but if you intend to do more stuff don't i guess?
