### ISSUE TITLE
Sort FAQ by # of times it has come up//been answered

### ISSUE THREAD

**Issue by Jeslis** [Satisfactory-Clips-Archive/Media-Search-Archive#2]
Effectively its the title; The idea/concept of a FAQ is to answer the most commonly asked questions.. and, in my opinion, watching the streams... the most commonly ANSWERED questions (eg; brought up by Jace/Snutt and answered) ARE the most commonly asked questions, and therefor should be filtered to the top.

That being said; there should probably be some sort of 'date decay' system, where, for example, things asked 10 times about update 3 do NOT eclipse things asked 6 times about update 5, 2 years later.

**Comment by SignpostMarv** [comment]
Date decay will need to be handled in a separate issue because that can end up being a looooooong conversation.
