### ISSUE TITLE
Add lists to youtube channel

### ISSUE THREAD

**Issue by MortalMercury** [Satisfactory-Clips-Archive/Media-Search-Archive#4]
Hello, I'm a follower of the Youtube channel this project has, this week you didn't upload the videos as public and I don't know why. I entered the webpage of the project and saw that the videos were uploaded to Youtube but placed as hidden, could you still add them to a playlist even if it's a hidden playlist with the link in the webpage pretty please?
(Of course, if it's a public playlist on the channel with hidden videos in them that would be even better)

**Comment by SignpostMarv** [comment]
yeah, my mistake- getting that sorted now.

changes to the schedule relating to the dayjob interefere with the previously-smooth workflow I had set up.

**Comment by SignpostMarv** [comment]
@MortalMercury  the [playlist](https://www.youtube.com/playlist?list=PLbjDnnBIxiEpvA0L00pfbJw2VksuWp_N4) was made public as part of the build process in 482e600

setting the videos public now.

**Comment by SignpostMarv** [comment]
all sorted, will add the youtube backlinks to the to-do list

**Comment by SignpostMarv** [comment]
@MortalMercury per #5, YouTube playlists are now listed as "External Link" under the topic title.
